insert into public.companies (
  id,
  company_id,
  display_name,
  legal_name,
  owner_name,
  street,
  postal_code,
  city,
  phone,
  email,
  website,
  vat_id,
  tax_number,
  finance_office,
  bank_name,
  account_holder,
  iban,
  bic,
  logo_path,
  brand_config
)
values
  (
    'punktlich-umzuege',
    'punktlich-umzuege',
    'Pünktlich Umzüge',
    'Pünktlich Umzüge',
    'Baschar Al Hasan',
    'Achillesstraße 52',
    '13125',
    'Berlin',
    '030 526 59 567',
    'info@punktlich-umzuge.de',
    'www.punktlich-umzuge.de',
    'DE454603297',
    'DE454603297',
    'Pankow/Weißensee',
    'Berliner Sparkasse',
    'Baschar Al Hasan',
    'DE75 1005 0000 0191 5325 76',
    'BELADEBEXXX',
    '/logo-punktlich-official.png',
    '{
      "primaryColor": "#f26b21",
      "secondaryColor": "#172026",
      "logoPath": "/logo-punktlich-official.png",
      "footerText": "Pünktlich Umzüge · Achillesstraße 52 · 13125 Berlin · Berliner Sparkasse · IBAN: DE75 1005 0000 0191 5325 76",
      "legalName": "Pünktlich Umzüge",
      "displayName": "Pünktlich Umzüge",
      "brandName": "Pünktlich Umzüge",
      "fullLegalLine": "Pünktlich Umzüge - Inhaber: Baschar Al Hasan"
    }'::jsonb
  ),
  (
    'schnell-sicher-umzug',
    'schnell-sicher-umzug',
    'Schnell Sicher Umzug',
    'Bashar Transport',
    'Baschar Al Hasan',
    'Anzengruber Straße 9',
    '12043',
    'Berlin',
    '+49 172 9573681',
    'kontakt@schnellsicherumzug.de',
    'schnellsicherumzug.de',
    'DE454603297',
    'DE454603297',
    'Pankow/Weißensee',
    'Berliner Sparkasse',
    'Baschar Al Hasan',
    'DE75 1005 0000 0191 5325 76',
    'BELADEBEXXX',
    '/schnell-sicher-umzug-logo.png',
    '{
      "primaryColor": "#5daaf0",
      "secondaryColor": "#0e2334",
      "logoPath": "/schnell-sicher-umzug-logo.png",
      "footerText": "Schnell Sicher Umzug · Bashar Transport - Inhaber: Baschar Al Hasan · Anzengruber Straße 9 · 12043 Berlin · Berliner Sparkasse · IBAN: DE75 1005 0000 0191 5325 76",
      "legalName": "Bashar Transport",
      "displayName": "Schnell Sicher Umzug",
      "brandName": "Schnell Sicher Umzug",
      "fullLegalLine": "Bashar Transport - Inhaber: Baschar Al Hasan"
    }'::jsonb
  )
on conflict (company_id) do update
set display_name = excluded.display_name,
    legal_name = excluded.legal_name,
    owner_name = excluded.owner_name,
    street = excluded.street,
    postal_code = excluded.postal_code,
    city = excluded.city,
    phone = excluded.phone,
    email = excluded.email,
    website = excluded.website,
    vat_id = excluded.vat_id,
    tax_number = excluded.tax_number,
    finance_office = excluded.finance_office,
    bank_name = excluded.bank_name,
    account_holder = excluded.account_holder,
    iban = excluded.iban,
    bic = excluded.bic,
    logo_path = excluded.logo_path,
    brand_config = excluded.brand_config;

insert into public.document_counters (company_id, document_type, year, current_number)
values
  ('punktlich-umzuege', 'offer', extract(year from now())::integer, 1),
  ('punktlich-umzuege', 'invoice', extract(year from now())::integer, 1),
  ('punktlich-umzuege', 'contract', extract(year from now())::integer, 1),
  ('punktlich-umzuege', 'job', extract(year from now())::integer, 1),
  ('schnell-sicher-umzug', 'offer', extract(year from now())::integer, 1),
  ('schnell-sicher-umzug', 'invoice', extract(year from now())::integer, 1),
  ('schnell-sicher-umzug', 'contract', extract(year from now())::integer, 1),
  ('schnell-sicher-umzug', 'job', extract(year from now())::integer, 1)
on conflict (company_id, document_type, year) do nothing;
